### ISSUE TITLE
Allow log flags other than log.LstdFlags

### ISSUE THREAD

**Issue by dhait** [lalamove/nui#5]
In the nlogger.New() func, the logger flags are hardcoded to log.LstdFlags.  This makes it difficult to modify the nlogger.Provider for logging.  Can you add the flexibility to specify the log flags to be used in a new logger?

**Comment by mikn** [comment]
Thanks for your input! We are considering opening this up. Our idea was that you are most likely using a logger in your project already such as zap, onelog or zerolog, and would only really want to have a way to comply to the interface. Thus we provided `BasicToStructured()`. We imagined the `New()` function is mostly a "test logger" or a "I don't care" kind of thing.

What's your reason for wanting to use the `New()` directly? And more specifically to control the `log.LstdFlags`?

**Comment by dhait** [comment]
Fundamentally, the standard Go library "log" does not meet the requirements of the interface, so it forces users to go to a third-party library such as the ones you mentioned.  And not all third-party loggers are compliant with your interface.

In a corporate setting, third-party open source projects are risky (unless they are Google or Apache), because you never know how long they are going to stay "alive".  We generally try to minimize the risk by using as few "external" Go packages as possible.
(Your "konfig" library is excellent, so we view it as worth the risk !)

I wanted to use New() directly because it appears to be the only way to use "log" without more wrapping.   And "log" is only useful if we can put more information in our log files; hence the need to include other flags.

Alternatively you might consider just providing a flexible, nlogger-compliant wrapper for "log".

**Comment by mikn** [comment]
Thanks for your appreciation! And okay, that makes perfect sense. I implemented a function `NewWithLog()` function that takes a `*log.Logger` from the standard library, so you can also reuse your own logger based on `log.Logger` if you need.
Does this satisfy your requirements?

**Comment by dhait** [comment]
Looks great, thank you!

**Comment by mikn** [comment]
I have merged to master and will create a release tag tomorrow. If you need it in the meanwhile, please track master. :)

**Comment by nishaad78** [comment]
Here is the new release tag for this feature: `v0.2.0`
